install.packages("remotes")
library(remotes)
install_version("tidyverse", "1.3.1")
install_version("readxl", "1.4.0")
install_version("gt", "0.6.0")
install_version("shiny","1.7.1")
install_version("shinyFiles","0.9.3")
install_version("psycModel","0.4.1")
install_version("R3port","0.2.4")
install_version("this.path","1.0.1")
install_version("tableHTML","2.1.0")
install_version("webshot", "0.5.3")
library(webshot)
webshot::install_phantomjs()

